# Generated by Django 3.1.6 on 2022-10-03 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('status', models.CharField(default='client', max_length=50)),
                ('temporary_code', models.CharField(default=None, max_length=6)),
                ('balance', models.IntegerField(default=1000000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('double_authentication', models.BooleanField(default=False)),
                ('double_authentication_code', models.CharField(default=None, max_length=6)),
                ('double_authentication_validated', models.BooleanField(default=False)),
                ('transaction_protection', models.BooleanField(default=False)),
                ('transaction_protection_code', models.CharField(default=None, max_length=6)),
                ('alert_mail', models.BooleanField(default=False)),
                ('company_name', models.CharField(default=None, max_length=100)),
                ('area_activity', models.CharField(default=None, max_length=100)),
                ('phone_number', models.CharField(default=None, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('amount', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=2)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payee', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_from_transaction', to='api.providers')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_from_paymentmethod', to='api.providers')),
            ],
        ),
        migrations.CreateModel(
            name='APIAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiUser', models.CharField(default=None, max_length=100)),
                ('apiKey', models.CharField(default=None, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiAccessOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
