# Generated by Django 3.1.6 on 2022-10-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='state',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='payer_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apiaccess',
            name='apiKey',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apiaccess',
            name='apiUser',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='area_activity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.FloatField(default=1000000),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='double_authentication_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='double_authentication_validated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='temporary_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='transaction_protection_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
